parameters:
  - name: environment
    displayName: The Environment to deploy the image
    type: string
    default: Stage
    values:
      - Stage
      - Prod
  - name: imageTag
    type: string
pool:
  vmImage: ubuntu-latest
trigger: none
name: '$(Date:yyyy).$(Date:MMdd)$(rev:.r)'
variables:  
  - name: environmentAlias
    ${{ if eq( parameters['environment'], 'Stage') }}:
      value: "test"
    ${{ if eq( parameters['environment'], 'Prod' ) }}:
      value: "prod"
stages:
      - stage: Test 
        displayName: Testing variables
        variables:
          - template: 'variables/env/${{ variables.environmentAlias }}/variables.yaml'        
        jobs:
          - job: Approval_Job_1
            displayName: ${{ parameters.environment }} Deployment Approval
            steps:
              - script: echo "Hello, world!"
          - job: Approval_Job_2
            displayName: ${{ parameters.environment }} Deployment Approval
            steps:
              - task: ManualIntervention@8
                displayName: 'Manual Intervention'
                inputs:
                  instructions: 'Please approve ${{ parameters.environment }} deployment validation.'
                  emailRecipients: |
                    gk.shinde@gmail.com
                  onTimeout: 'reject'  
                env:
                  minimumApprovals: 1
                timeoutInMinutes: 1440      
