apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s-spring-ms-demo2
  name: k8s-spring-ms-demo2
spec:
  ports:
  - name: spring-ms-demo2-service
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: k8s-spring-ms-demo2
  type: ClusterIP
status:
  loadBalancer: {}